### ISSUE TITLE
Missing "!" in README.md

### ISSUE THREAD

**Issue by Daniel-Gill** [Railway-Op-Sim/UN-Template#1]
Hi,

I don't know if this is on purpose, but there is a missing exclamation mark on the image to change it from a link.

If this is on purpose then it might be worth putting a note in there to add it, I just spent 5 minutes trying to find why my image wasn't working! 🤦‍♂️

Dan

**Comment by zarethrex** [comment]
Woops! My bad, sorry about that, well noted!
